### ISSUE TITLE
Release notes for 0.4.0?

### ISSUE THREAD

**Issue by dlong500** [jaredhanson/passport#599]
I understand that I can look through the actual commit history to see specifically what has changed, but is v0.4.0 a breaking change from 0.3.2?

Any chance of getting some summary of changes?

**Comment by jaredhanson** [comment]
See #598.

**Comment by jorrit** [comment]
In any case, I would like to request the addition of release notes for each release. It is a chore for the maintainers, but it is very welcome for all users, as the presence of these issues indicates.

**Comment by semy** [comment]
For me after upgrading to 0.4.0 I get a bug:

`error: Sending 500 ("Server Error") response: 
 TypeError: next is not a function
    at attempt (/Users/sg/web/dev/crypto/bitcoin/project/node_modules/passport/lib/middleware/authenticate.js:186:32)
    at authenticate (/Users/sg/web/dev/crypto/bitcoin/project/node_modules/passport/lib/middleware/authenticate.js:362:7)`

Maybe it's better to check this!

**Comment by jaredhanson** [comment]
@semy - Could you provide any details about how you are using passport that results in that error?  This may be an application-level bug, but it is impossible to pinpoint without further information.

**Comment by pronebird** [comment]
I am updating from 0.2.2 -> 0.4. What a minefield. Is it that hard to maintain a changelog? Thanks.

**Comment by dilipfrancis** [comment]
I am getting the same error as semy:
TypeError: next is not a function
    at attempt (/eng/software/nodeapi/node_modules/passport/lib/middleware/authenticate.js:186:32)
    at authenticate (/eng/software/nodeapi/node_modules/passport/lib/middleware/authenticate.js:362:7)

**Comment by franc23** [comment]
https://github.com/ga-wdi-exercises/project3/issues/52 is the resolution for this. Need to pass in "next" as the third parameter.

**Comment by robross0606** [comment]
I'm in the same boat here.  Trying to upgrade from 0.4.2 to 0.7.0 and there's no documentation anywhere about breaking changes short of directly reviewing commits.
