### ISSUE TITLE
req.session.regenerate is not a function since upgrade to 0.6.0

### ISSUE THREAD

**Issue by nickyblissAviva** [jaredhanson/passport#907]
We have been using passport for some time within our application and have had no issues but once upgraded from 0.5.2 to 0.6.0 we are suddenly seeing an error when submitting authentication.

```js
C:\stash\NTTSites\sites\fw-standards\node_modules\passport\lib\sessionmanager.js:28
  req.session.regenerate(function(err) {
              ^

TypeError: req.session.regenerate is not a function
    at SessionManager.logIn (C:\stash\NTTSites\sites\fw-standards\node_modules\passport\lib\sessionmanager.js:28:15)
    at IncomingMessage.req.login.req.logIn (C:\stash\NTTSites\sites\fw-standards\node_modules\passport\lib\http\request.js:39:26)
    at Strategy.strategy.success (C:\stash\NTTSites\sites\fw-standards\node_modules\passport\lib\middleware\authenticate.js:256:13)
    at verified (C:\stash\NTTSites\sites\fw-standards\node_modules\passport-local\lib\strategy.js:83:10)
    at Strategy.runAuth [as _verify] (C:\stash\NTTSites\sites\fw-standards\utils\passport-authentication.js:60:10)
```

Our passport-authentication.js just initialises passport within expressJS and sets some local strategies.

I have rolled back to 0.5.3 and our application works fine again.

### Environment

* Operating System: Windows 10
* Node version: 16.13.2
* passport version: 0.6.0

**Comment by nickyblissAviva** [comment]
cookie-session 2.0.0

**Comment by jaredhanson** [comment]
Thanks for the report.  This is a duplicate of #904.  I'd recommend pinning to 0.5.x, until I've had a chance to release an update with the new features described on the initial issue.

**Comment by spraju92** [comment]
Passport 0.5.0 has a significant vulnerability, and when we update to 0.6.0, we see the error "TypeError: req.session.regenerate is not a function." Does that mean that anything relating to the session create issue needs to be manually edited?

**Comment by raphaelpreston** [comment]
Any update for March 2023? I see that @VottonDev has a fix in their separate repo..

**Comment by hier01** [comment]
@VottonDev, what's the best way to apply the fix in joeyguerra's fork?

**Comment by VottonDev** [comment]
> @VottonDev, what's the best way to apply the fix in joeyguerra's fork?

Well I've changed my package.json passport to
```"passport": "github:joeyguerra/passport#missing-regenerate-on-req",```

The PR for the fix is here, which is how I found it:
https://github.com/jaredhanson/passport/pull/947

**Comment by japthind** [comment]
Hi All,

Can anyone please confirm the status of this issue as this is currently blocking one of our production deployments? Is there a permanent fix for this or do we need to downgrade to 0.5.x version?

**Comment by faizur11786** [comment]
I encountered a similar problem with version 0.6 of Passport. To resolve it, I downgraded to version 0.5.0

**Comment by imartinezmorales-loom** [comment]
I ended up resolving this issue for our upgrade to passport 0.6.0 by stubbing the `regenerate` and `save` methods. I patched the dependency in our repository in the `lib/sessionmanager.js` file as such: 

```diff
  options = options || {};

+  this._delegate = options.delegate || {
+        regenerate: function(req, cb) {
+            cb();
+        },
+        save: function(req, cb) {
+            cb();
+        }
+    };
```

And then propagating those changes to the various calls to `save` and `regenerate` in the file.

**Comment by recursiveway** [comment]
@imartinezmorales-loom do we simply have to add these lines or have to change/remove something as well

**Comment by imartinezmorales-loom** [comment]
@recursiveway - I actually ended up writing a middleware function that I pull into our express server. The middleware function is just a stub similar to the one above:

```javascript

export const passportMiddleware = (request, response, next) => {
  if (request.session && !request.session.regenerate) {
    request.session.regenerate = cb => {
      cb();
    };
  }

  if (request.session && !request.session.save) {
    request.session.save = cb => {
      cb();
    };
  }

  next();
};


```

**Comment by tonmoydeb404** [comment]
instead of using **`cookie-session`** I've used **`express-session`** as a session middleware with the latest passport package and this solves the problem.

**Comment by radoslavirha** [comment]
@tonmoydeb404 but they serve different purposes, it's not a solution.

**Comment by tanosaur** [comment]
Can't believe this still isn't fixed?

**Comment by AlvesJorge** [comment]
+1 Above

**Comment by raulrene** [comment]
> instead of using **`cookie-session`** I've used **`express-session`** as a session middleware with the latest passport package and this solves the problem.

Yes but it should also work with `cookie-session`, it did until 0.5.0. It's not so easy for everyone to switch the session manager, especially on large projects. Hopefully this gets fixed sometime soon

**Comment by DaneeSkripter** [comment]
So should I change session manager from ```cookie-session``` to ```express-session```, or stay on passport 0.5?

**Comment by lalitkishork73** [comment]
@drebel, it shows me, **Error: req#logout requires a callback function**

**Comment by yevon** [comment]
Any news for this one? I'm getting same error under passport 0.7.0 and cookie-session 2.1.0

**Comment by daneedev** [comment]
@yevon 
> Any news for this one? I'm getting same error under passport 0.7.0 and cookie-session 2.1.0

Hey, the cookie-session isn't officialy supported by passport. So I don't think they will ever make support for it. I used to use cookie-session, but I switched to express-session and it works very well. I suggest you to switch too.

Have a nice day,
Daniel Kroufek

**Comment by yevon** [comment]
> @yevon
> 
> > Any news for this one? I'm getting same error under passport 0.7.0 and cookie-session 2.1.0
> 
> Hey, the cookie-session isn't officialy supported by passport. So I don't think they will ever make support for it. I used to use cookie-session, but I switched to express-session and it works very well. I suggest you to switch too.
> 
> Have a nice day, Daniel Kroufek

Thanks for that! I will try to replace it

**Comment by asaxena1415** [comment]
> > @yevon
> > > Any news for this one? I'm getting same error under passport 0.7.0 and cookie-session 2.1.0
> > 
> > 
> > Hey, the cookie-session isn't officialy supported by passport. So I don't think they will ever make support for it. I used to use cookie-session, but I switched to express-session and it works very well. I suggest you to switch too.
> > Have a nice day, Daniel Kroufek
> 
> Thanks for that! I will try to replace it

express-session does not store cookies on the client side, the session gets destroyed every time the serve restarts, this is not a solution.

**Comment by zerone0x** [comment]
> express-session

Thanks for your suggestion

**Comment by daneedev** [comment]
@yevon 
> express-session does not store cookies on the client side, the session gets destroyed every time the serve restarts, this is not a solution.

The solution for this is making a database to save user sessions, for example really simple is SQLite.

**Comment by Chillorain** [comment]
> Я получаю следующую ошибку, когда выхожу из своего приложения. Я использую модуль express-session для управления сеансами. Согласно вышеизложенному обсуждению, есть ли постоянное исправление для этого или мне нужно понизить версию Passport 0.6.0
> 
> /node_modules/passport/lib/sessionmanager.js:83 req.session.regenerate(function(err) { ^ TypeError: Невозможно прочитать свойства undefined (чтение 'regenerate') в Immediate. (/node_modules/passport/lib/sessionmanager.js:83:17) в process.processImmediate (node:internal/timers:471:21)

Вы смогли решить данную проблему?

**Comment by ecofi** [comment]
What is the status here? I'm running into the same issue ... and no, I don't want to store session data on server side. Would info from maintainer whether this is going to be fixed or remains unsolved.

**Comment by kenneth-ge** [comment]
Any update in 2025? I'm encountering the same issue with google oauth2

**Comment by daneedev** [comment]
The solution like I said earlier to migrate from ```cookie-session``` to ```express-session```. It works exactly the same, and doesn't have any issues. Could someone mark this issue as resolved? 

Thanks,
Daniel

**Comment by ecofi** [comment]
> The solution like I said earlier to migrate from `cookie-session` to `express-session`. It works exactly the same, and doesn't have any issues. Could someone mark this issue as resolved?
> 
> Thanks, Daniel

No, it is not! It seems you do not understand how session works. Cookie-session stores only on client side. No storage is required for the server side (i.e. back end) and it is much faster. Express-session requires session storage on the server side (memory, database or in files). This is a huge difference! Not everybody likes to run another service on the back-end as this requires more compliance efforts, i.e. more costs. For example, typical you need to run the session storage (redis, mongodb or whatever storage service) on another server for security issues.

**Comment by tanosaur** [comment]
+1 @ecofi

**Comment by skylord220** [comment]
+1 for prev comment. Also using cookie-session (fork with encryption and compression) for lightweight sessions in distributed application without seprate DB. The best workaround for us was to add few lines in a middleware after passport.js init like in https://github.com/jaredhanson/passport/issues/907#issuecomment-1697590189

**Comment by ANGELA-PARGA** [comment]
Any update??? I have the same issue, I am using express-session, 1.18.1, MongoDB to store sessions and passport 0.70. One day it was working just fine and now I got the same error. I just added a req.session.destroy to delete the session and stop working

**Comment by Toxiapo** [comment]
Maybe related, but I am on passport@0.7.0, express-session@1.18.1 and received the following error when calling req.session.destory(). passport@0.5.0 seems to be working

```ts
TypeError: Cannot read properties of undefined (reading 'regenerate')
    at Immediate.<anonymous> (/node_modules/passport/lib/sessionmanager.js:83:17)
    at processImmediate (node:internal/timers:483:21)
[ERROR] 00:52:34 TypeError: Cannot read properties of undefined (reading 'regenerate')

```
