### ISSUE TITLE
"TypeError: req.login is not a function"

### ISSUE THREAD

**Issue by feross** [jaredhanson/passport#436]
Getting lots of "TypeError: req.login is not a function" and "TypeError: req.logout is not a function" since upgrading to 0.3.1.

Are you sure the fanciness with prototypes that you added in 0.3.1 is working correctly?

**Comment by jaredhanson** [comment]
It passes all my tests.  Let's see if any additional reports come in.  In the meantime, any debugging you can do to isolate the issue would be appreciated.  Thanks!

**Comment by jaredhanson** [comment]
@feross Can you update to `passport@0.3.2` and let me know if it works?  Merging #437 should have fixed the issue.

**Comment by SamMorrowDrums** [comment]
Yep, this is working now!

**Comment by feross** [comment]
Works for me too!

**Comment by Cat-The-Developer** [comment]
nah, do not work for me in next js
